language: node_js
before_script:
  - npm install -g npm
  - npm install -g npm-ci
  - npm install webpack
  - npm install uglifyjs-webpack-plugin
cache:
  directories:
  - node_modules
node_js:
- "12"
script:
  - npm run build
  - npm run build:prod